# Generated by Django 5.2.1 on 2025-05-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sellerprofile_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
