# Generated by Django 5.2.1 on 2025-05-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_buyerprofile_address_sellerprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='day',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='selected_day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True),
        ),
    ]
